# Generated by Django 3.0.3 on 2020-05-19 06:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cultivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.IntegerField(default=1, verbose_name='codigo')),
                ('latitud', models.IntegerField(default=1, verbose_name='latitud')),
                ('longitud', models.IntegerField(default=1, verbose_name='longitud')),
                ('area', models.IntegerField(default=1, verbose_name='area')),
                ('producto', models.CharField(max_length=20, verbose_name='producto')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
